// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eijqehmzaffrwianhcto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpanFlaG16YWZmcndpYW5oY3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzQ1MzQsImV4cCI6MjA2MjAxMDUzNH0.-ZgqOAOCcUaEhy-8xXM_RrBCo0E1uCoPg0f93M7LPew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);